version: '3.5'

services:
    pgadmin:
        container_name:  ${COMPOSE_PROJECT_NAME}_pgadmin
        image: dpage/pgadmin4
        volumes:
            - pgadmin_volume:/var/lib/pgadmin:cached
        depends_on:
            - postgis
        links:
            - postgis:pgdb
        ports:
            - ${DB_ADMIN_PORT}:80
        restart: unless-stopped
        networks:
            - net_db
        environment:
            PGADMIN_DEFAULT_EMAIL: default@email.com
            PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
volumes:
    pgadmin_volume:
