version: '3.5'

services:
    mercure:
        image: dunglas/mercure:v0.8
        container_name: ${COMPOSE_PROJECT_NAME}_mercure
        ports:
            -  ${MERCURE_PORT}:80
        environment:
            JWT_KEY: ${MERCURE_JWT_PASSPHRASE}
            DEMO: 1
            ALLOW_ANONYMOUS: 1
            CORS_ALLOWED_ORIGINS: '*'
        networks:
            - net_backend
    php:
      links:
        - mercure
